add docker support and fix bugs with registration
Denis-Balako/Online-Book-Store pull request #10
Opened 2023-09-19 13:42 UTC by Denis-Balako

2023-09-20 06:52 UTC, Dimagaa requested changes
Well done

2023-09-20 06:52 UTC, Dimagaa commented on .env
> +DEBUG_PORT=5005
Add empty line

2023-09-22 13:07 UTC, andrii-hoienko requested changes
Nice, but some improvements required

2023-09-22 13:07 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/07-add-users-with-roles-in-user-table.yaml
> +                  valueNumeric: 1
It is better to use valueComputed

2023-09-26 08:29 UTC, nacenik approved these changes
LGTM! 👍

2023-09-26 09:26 UTC, merged