Dev 6
Denis-Balako/Online-Book-Store pull request #6
Opened 2023-09-09 20:10 UTC by Denis-Balako

2023-09-10 18:54 UTC, CodeWebWeaver requested changes
This code is absolutely amazing. I haven't seen such beautiful code in my life. I want to cherish it and share it with my children someday. I want your autograph. But there is still one issue

2023-09-10 18:54 UTC, CodeWebWeaver commented on src/main/java/com/balako/onlinebookstore/service/impl/UserServiceImpl.java
> +        return userMapper.toUserResponse(savedUser);
You call 
User user = userMapper.toModel(request);
and then do mapper work. Why?

2023-09-11 04:50 UTC, CodeWebWeaver approved these changes
Nice!

2023-09-11 06:25 UTC, CodeWebWeaver requested changes

2023-09-11 06:25 UTC, CodeWebWeaver commented on src/main/java/com/balako/onlinebookstore/exception/CustomGlobalExceptionHandler.java
>  import java.time.LocalDateTime;
Wrong import:
use springframework.security

2023-09-11 08:01 UTC, CodeWebWeaver approved these changes
Good

2023-09-11 15:25 UTC, vovasalyha approved these changes
GJ. Take a look on few suggestions.

2023-09-11 15:25 UTC, vovasalyha commented on src/main/java/com/balako/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        body.put("timestamp", LocalDateTime.now());
You're creating the same map for each error response. I suggest to define the error response formate and create a separate class for error response.

2023-09-11 15:25 UTC, vovasalyha commented on src/main/java/com/balako/onlinebookstore/model/Role.java
> +public class Role {
Table name?

2023-09-11 20:05 UTC, merged